version: "3.8"

services:
  nestapp:
    build: ./
    ports: 
      - "3000:3000"
    env_file: 
      - .development.env
    depends_on:
      - postgresdb

  postgresdb:
    image: 'postgres'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .development.env

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .development.env
    ports: 
      - 5050:80
    depends_on:
      - postgresdb
volumes:
 pgdata: 