import {
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  OneToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { OrderDetails } from './orderDetails.entity';
import { Users } from './users.entity';

@Entity({
  name: 'ORDERS',
})
export class Orders {
  /**
   * Autogenerated UUID.
   * @example '15707987-2981-4dd6-a99b-443caea1d6bd'
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * Autogenerated date.
   * @example '2024-04-22T09:32:47.740Z'
   */
  @Column()
  date: Date;

  @ManyToOne(() => Users, (user) => user.orders)
  @JoinColumn({ name: 'user_id' })
  user: Users;

  @OneToOne(() => OrderDetails, (orderDetails) => orderDetails.order)
  orderDetails: OrderDetails;
}
